/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;

/**
 *
 * @author Damian
 */
public class VPrincipal extends javax.swing.JFrame {

    public static final String BOTON_AGREGAR_ANIMALES="agregar animales";
    public static final String BOTON_AGREGAR_VETERINARIOS="agregar veterinarios";
    public static final String BOTON_CALCULAR_ALIMENTOS="calcular alimento";
    
    
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarAnimales = new javax.swing.JButton();
        btnAgregarVeterinarios = new javax.swing.JButton();
        btnCalcularAlimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema del Zoologico");

        btnAgregarAnimales.setText("Agregar Animal");
        btnAgregarAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAnimalesActionPerformed(evt);
            }
        });

        btnAgregarVeterinarios.setText("Agregar Veterinario");

        btnCalcularAlimento.setText("Calcular Allimento");
        btnCalcularAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAlimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcularAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarVeterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAgregarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarVeterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAnimalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarAnimalesActionPerformed

    private void btnCalcularAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularAlimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAnimales;
    private javax.swing.JButton btnAgregarVeterinarios;
    private javax.swing.JButton btnCalcularAlimento;
    // End of variables declaration//GEN-END:variables

    public void setControlador(Controlador aThis) {
        
        btnAgregarAnimales.setActionCommand(BOTON_AGREGAR_ANIMALES);
        btnAgregarVeterinarios.setActionCommand(BOTON_AGREGAR_VETERINARIOS);
        btnCalcularAlimento.setActionCommand(BOTON_CALCULAR_ALIMENTOS);
        btnAgregarAnimales.addActionListener(aThis);
        btnAgregarVeterinarios.addActionListener(aThis);
        btnCalcularAlimento.addActionListener(aThis);
        
        
    }

    public void ejecutar() {
        this.setVisible(true);
    }
}
